# Archlinux
# Build Lightly from release tag and publish .zst package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
env:
  PKGBUILD: $GITHUB_WORKSPACE/.github/assets/pkgbuild/PKGBUILD
jobs:
  build-release:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Checkout local
        uses: actions/checkout@v4.2.0
        with:
          repository: ${{ github.repository }}
          sparse-checkout: .github
          sparse-checkout-cone-mode: false
      - name: System update
        run: pacman -Syu --noconfirm
      - name: Install sudo, git and compile dependencies
        run: |
          pacman -Sy sudo git binutils make gcc pkg-config fakeroot \
          cmake extra-cmake-modules qt6-base \
          kdecoration qt6-declarative kcoreaddons \
          kcmutils kcolorscheme kconfig kguiaddons \
          kiconthemes kwindowsystem --noconfirm
      - name: Setup build user
        run: |
          useradd builduser -m # Create the builduser
          passwd -d builduser # Delete the buildusers password
          printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers # Allow the builduser passwordless sudo
      - name: Update PKGBUILD file with new checksum and git tag values
        run: |
          # update tag with latest version
          mkdir /var/tmp/lightly-archlinux
          cp ${{ env.PKGBUILD }} /var/tmp/lightly-archlinux
          sed -i "s/.*pkgver=.*/pkgver=${{ inputs.version }}/" /var/tmp/lightly-archlinux/PKGBUILD
      - name: Change permissions of build directory
        run: | 
            chown builduser:builduser -R /var/tmp/lightly-archlinux
      - name: Generate package checksum
        run: sudo -u builduser bash -c 'cd /var/tmp/lightly-archlinux; makepkg -g >> PKGBUILD'
      - name: Build package
        run: |
          sudo -u builduser bash -c 'cd /var/tmp/lightly-archlinux; makepkg -s'
          zst_file=$(find /var/tmp/lightly-archlinux -name "*.zst*")
          publish_filename=lightly-${{ inputs.version }}-x86_64.pkg.zst
          mv "$zst_file" $publish_filename
          echo "ZST_ASSET=$publish_filename" >> "$GITHUB_ENV"
      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ZST_ASSET }}

